language: java

jdk:
  - oraclejdk8
  
addons:
 sonarcloud:
  organization: "3pillar-labs-github"
  token:
   secure: "yuCJcG9aVn3JdCDmgQq5pEA5WtFuIwyQUlF/mXldK0GcvxPE0YG4EF831FGTd3/SmQm7ee1j15TiGZDenDATJz848itq2d3uDpbm8o39nXQSFvjRnBjnn/S5kJVxpwLQMaIbPbnm8cdfk1aZeXGrudbPDzEkJlL/KRXRibxXgIfIbEpuAFRySfWL7yXXkMk2QuEHNrq+5JtFBlKB5LPCoSI3Ogps4V0/f5SPMfFV/kUSgD1WcBVaVkc3FECprxRtrpK2uWOEwtL+142pWD1ZFiQ9WTeQeLyiOIhQ3bc1Y19AIOOv6A+5bojzrbf/7GSuH3Bi2yQX0jtaRw8XEKhxmAbIRBoNjgiofgYpCHhiDDgqqk0Xi0EwNeaRL2inrEwP4kyKm9xPlsxfyuxyEyG2rszkrw/lf0kOJIn0DXMmTJl7DluQFHsTdR1tJRLRRkUvVixjms6VICAoTPMeV08RBL0wziIgqR1YQAAiTBo5VmaSaOxyzFDB/edGL7/Wj2eBmFDrHdW8G+zK0t34xbAHETYotmUAWEvMdRqDebZP+t/cRBXxMnXGtslRb/wR1IPqqhb5e4/5hsHvWx7gHWobAtSE1h3Q2AgK7SUKRir+0kDDzih1/iOe2HimdUFDMql5E3ejQCK37Qt8xWy3eAC2heCQG5MWDw2HA1QoRao2IUk="
  github_token:
   secure: "xrSjBA31jfHdzDUK8m2uWIrWtRTAXkuASCbTZPjb3+0Gq9s/1k/jYJKTS9C+fRSE1PFFoY9yyoSsSbhBjlnFL39+smIQhyOgiW+C55/LbuladZxQXYwkw1awIaM+wlJ2xYef4uoChZgm37EDRI5CAYbQpNbkzd1L64GFTRKBk6ELrD6kMk37b84TuTcek2cPbCW/pHGCxhHBncxHGEz0kmAmaTWx3GY5tEoO71I+huLSH99vafroGzstVVB+nS+0RLK0W8eI/Y1yhYq0mQJ/CmqjN7aR2cln32fbzWPdwhy1aiGL4GaC94NgQimZ64u2odu0xzFuxMJdbBU1TcDkwKeoDm2pDwYMzfDQDKOsVyTYvztlcWqnB6yJew36dw+PqaV9J17dHCt8pRuP7XNO6vaSzhokkW7YWx0Ht9+hczX0m8wgT1JUdAojZtRSNvho6/uByhxqEmYop1cAw/vcRSyeycpwEVKq5IyHiSiq1bZT5bfBbEd6nstztWwsNFTyTAFzyz7qB+oku/vdFGwlypaZdLR+Ae5SchmECJ0blE6/KeN3kvVjb0EscDIwjZ8D5sNRK2xC6bSjehb9U2bRPmat7sZlmYJ/jjHCH+30UPOAFdcCpgl6jXvTI50Bop5/JWMYPER+j8o5ZeqdzJtOntPc+TJJtx+foOVwl+Y6L7A="

script:
  - sonar-scanner
